---
title: "Mapas de delitos patrimoniales y extorsión"
author: "Carlos Crespín"
date: "2024-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(magrittr)
library(rio)
library(sp)
library(ggplot2)
library(rgdal)
library(ggplot2)
xtr=import("SIDPOL_dpt_extorsion.xlsx")
mapDPT=sf::read_sf("DEPARTAMENTO.shp")
ggplot(mapDPT) + geom_sf()
```

Limpieza de data de extorsiones
```{r}
#A nivel histórico se intentará crear un mapa para ver si se condice con los otros
#realizados
xtr=filter(xtr, PMODALIDADES=="Extorsión")
xtr=xtr%>%
  group_by(DPTO_HECHO_NEW) %>%
  summarise(casos=sum(n_dist_ID_DGC))
names(xtr)=c("DEPARTAMEN","casos")
```

```{r}
setdiff(mapDPT$DEPARTAMEN,xtr$DEPARTAMEN)
```
```{r}
setdiff(xtr$DEPARTAMEN,mapDPT$DEPARTAMEN)
```
```{r}
xtr[xtr$DEPARTAMEN=='LIMA METROPOLITANA','DEPARTAMEN']='LIMA'
```

Merge de la data
```{r}
mapEXTOR=merge(mapDPT,xtr)
```


```{r}
summary(mapEXTOR$casos)
```


Realizaremos el primer mapa
```{r}
ggplot(mapEXTOR) +
    geom_sf(aes(fill = casos))
```

```{r}
library(ggplot2)

# Crear el gráfico de mapa de calor
grafico <- ggplot(mapEXTOR) +
  geom_sf(aes(fill = casos)) +
  scale_fill_gradient(low = "white", high = "darkred")  # Invertir la escala de colores

# Mostrar el gráfico
print(grafico)
```

Se expresa lo mencionado en los otros gráficos: después de Lima, Trujillo, Lambayeque
y La Libertad tienen una gran cantidad de denuncias por delitos de extorsión y 4
patrimoniales


































































